Fix out-of-cards crash on server.
Stack trace:

java.lang.IllegalStateException: No cards available!
      at com.forerunnergames.tools.common.Preconditions.checkIsTrue(Preconditions.java:41) ~[peril-server-0.1-SNAPSHOT.jar:na]
      at com.forerunnergames.peril.core.model.card.DefaultCardDealer.take(DefaultCardDealer.java:61) ~[peril-server-0.1-SNAPSHOT.jar:na]
      at com.forerunnergames.peril.core.model.card.DefaultCardModel.giveCard(DefaultCardModel.java:68) ~[peril-server-0.1-SNAPSHOT.jar:na]
      at com.forerunnergames.peril.core.model.GameModel.endPlayerTurn(GameModel.java:358) ~[peril-server-0.1-SNAPSHOT.jar:na]
      at com.forerunnergames.peril.core.model.state.GameStateMachineAdvancePlayerTurnState.onEntry(GameStateMachineAdvancePlayerTurnState.java:33) ~[peril-server-0.1-SNAPSHOT.jar:na]
      at com.forerunnergames.peril.core.model.state.GameStateMachineAdvancePlayerTurnState.onEntry(GameStateMachineAdvancePlayerTurnState.java:6) ~[peril-server-0.1-SNAPSHOT.jar:na]
      at com.stateforge.statemachine.algorithm.StateOperation.walkTreeEntry(StateOperation.java:63) ~[peril-server-0.1-SNAPSHOT.jar:na]
      at com.stateforge.statemachine.algorithm.StateOperation.processTransitionEnd(StateOperation.java:144) ~[peril-server-0.1-SNAPSHOT.jar:na]
      at com.forerunnergames.peril.core.model.state.GameStateMachinePlayerTurnState.onEndPlayerTurnRequestEvent(GameStateMachinePlayerTurnState.java:69) ~[peril-server-0.1-SNAPSHOT.jar:na]
      at com.forerunnergames.peril.core.model.state.GameStateMachineGameHandlerContext.onEndPlayerTurnRequestEvent(GameStateMachineGameHandlerContext.java:140) ~[peril-server-0.1-SNAPSHOT.jar:na]
      at com.forerunnergames.peril.core.model.state.GameStateMachineOperatingState.onEndPlayerTurnRequestEvent(GameStateMachineOperatingState.java:171) ~[peril-server-0.1-SNAPSHOT.jar:na]
      at com.forerunnergames.peril.core.model.state.GameStateMachineContext$10.run(GameStateMachineContext.java:231) ~[peril-server-0.1-SNAPSHOT.jar:na]
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_72]
      at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_72]
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_72]
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_72]
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
      at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]

- Caused by having enough players but few enough cards in order to drain
  the deck and discard pile but still not have enough to trade-in.

- Check to see if a card can be given to a player before actually giving
  it, logging a warning in that case. The game should still be playable
  if cards run out.

- The only way to obtain more cards would be to eliminate other players
  with cards.

- The minimum card count will always be enough to trade-in because there
  is one card per country + 2 wilds, and the minimum country count is
  10, making the minimum card count 12.

- 12 cards doesn't go far among the max of 10 players, however...