Fix Travis build (Use JDK 8).
Problem:

  Build fails with:

    java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

  after upgrading Gradle & Android Gradle plugin via
  ad60125b4783cf6dd5f4f76c5cc28e751ff8fd14.

Solution:

- Use JDK 8 instead of 7 in Travis build.

diff --git a/.travis.yml b/.travis.yml
index 119cee1..5011607 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,7 +18,7 @@
 sudo: false
 install: true
 language: android
-jdk: oraclejdk7
+jdk: oraclejdk8

 android:
   components: